version: "3.7"
services:
  logs:
    # image: tianon/true:latest (docker/fig#919)
    image: busybox:latest
    volumes:
      - /var/log/hipache
      - /var/log/nginx
    command: /bin/echo
    depends_on:
      - redis
